name: Deploy API

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Login AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: us-east-1

      - name: Login ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build docker image
        run: |
          docker build -t event-api .

      - name: Tag image
        run: |
          docker tag event-api:latest $ECR_REPOSITORY:latest

      - name: Push image
        run: |
          docker push $ECR_REPOSITORY:latest

      - name: Deploy ECS
        run: |
          aws ecs update-service \
            --cluster event_management_cluster-ecs \
            --service event_management_service \
            --force-new-deployment