name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types: [opened]

jobs:
  test-validation:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
        dotnet-quality: 'preview'
    - name: Restore dependencies
      run: dotnet restore EventManagement/EventManagement.slnx
    - name: Run tests
      run: dotnet test EventManagement/EventManagement.slnx --no-restore --verbosity normal
    - name: Test results
      if: failure()
      run: exit 1

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
        dotnet-quality: 'preview'
    - name: Restore dependencies
      run: dotnet restore EventManagement/EventManagement.slnx
    - name: Build
      run: dotnet build EventManagement/EventManagement.slnx --no-restore